fieldLayouts:
  46fa3ce8-5d1f-423c-a9ce-9b07c1e58c73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 127c7e5d-c850-419f-83ec-441a62acf705
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: d00a82cf-f3fe-4dfb-921e-8b8439af62de
            userCondition: null
          -
            elementCondition: null
            fieldUid: 23fbe8f3-d0a4-499e-9bdf-1d2dc5a999f5 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 450b177a-f9b7-4ad0-85e8-a5fc72ab9825
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3d09627-c645-48dc-8a0c-c1323a8aeefe # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4472a2c4-8cc8-48bf-b1ae-f8635a19f7e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Form
            type: craft\fieldlayoutelements\Heading
            uid: fca11691-96a5-415e-835f-f6bc63174665
            userCondition: null
          -
            elementCondition: null
            fieldUid: 3ab0bfb1-c5e0-447f-9f41-2fcc08d15e94 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04c2ae6f-4ee7-4d9a-b642-9511a45ad9d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 73a343fd-f352-4fc7-9f37-699f9b425e06
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c216cc1-6bef-4496-a511-d619bfcd210d # Seo Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 322cfd86-b7e4-43cc-877c-76822523064b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4319f7b2-864d-4828-bb78-760e19c274fe
        userCondition: null
handle: contact
hasTitleField: true
name: Contact
section: a94c302a-1da9-4e98-96b1-36d23ce0235b # Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
