fieldLayouts:
  73bdaee5-80f1-4c84-96f9-a3978531ed64:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: af003c4a-37be-4d1c-ace9-dc65b5bd4cf3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Hero
            type: craft\fieldlayoutelements\Heading
            uid: f527dac5-c68a-4052-ae7b-085b977938ec
            userCondition: null
          -
            elementCondition: null
            fieldUid: 23fbe8f3-d0a4-499e-9bdf-1d2dc5a999f5 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0404b00e-9dfd-4303-906e-5598fa8ffbf4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d3d09627-c645-48dc-8a0c-c1323a8aeefe # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31d2802f-9b88-40b8-8edd-f3dcaa41f80f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Content
            type: craft\fieldlayoutelements\Heading
            uid: 36051a95-e064-4c4e-bc28-e70a58165cf2
            userCondition: null
          -
            elementCondition: null
            fieldUid: 4fd5d92e-484c-47a3-b63b-5443cb2736db # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1f0fedb-d600-492f-bad4-fcae00da4ce3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5078bd5a-d825-4f83-a810-47509aed4066
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c216cc1-6bef-4496-a511-d619bfcd210d # Seo Settings
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80b72f21-c68d-4b17-bc8e-20e03681e143
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 96eb80ea-af62-47de-bc03-918352398359
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 745244db-cd1b-4b14-ab0f-07d6ddcf070f # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
