field: 4fd5d92e-484c-47a3-b63b-5443cb2736db # Content
fieldLayouts:
  3091eff8-e53d-42bb-bf51-7e979b61cde0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3329f87e-3071-4db1-b35b-83cb0f7cc74c # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7aa11472-bcb2-4ab0-94e9-f5ecc8e44452
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 94d2a39a-d6b0-46e7-bad6-e1023c6893e5 # Headline Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d95f1039-be4f-4137-892e-a35b6f4f7048
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 65b08be4-872a-4753-bd26-429883d6d61f
        userCondition: null
fields:
  94d2a39a-d6b0-46e7-bad6-e1023c6893e5: # Headline Variant
    columnSuffix: bdwkydpj
    contentColumnType: string(2)
    fieldGroup: null
    handle: headlineVariant
    instructions: null
    name: 'Headline Variant'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H4
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H5
            -
              - value
              - h5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H6
            -
              - value
              - h6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  3329f87e-3071-4db1-b35b-83cb0f7cc74c: # Headline
    columnSuffix: hmxwdglk
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: headline
name: Headline
sortOrder: 1
