field: 4fd5d92e-484c-47a3-b63b-5443cb2736db # Content
fieldLayouts:
  1822f403-bd87-4a6d-a3d3-6e244caaeab8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 25d4c40f-03b6-4c00-bda2-7849d4d80197 # Link Information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64653355-5e22-4590-939a-450031392337
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 074609d1-90b2-4a51-a98f-a64d2dc87363 # Link Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48f56f50-996f-4960-a3a4-c83b28a2223c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: ac0b5446-0518-4f55-8cdb-d3aac65864ad
        userCondition: null
fields:
  25d4c40f-03b6-4c00-bda2-7849d4d80197: # Link Information
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkInformation
    instructions: null
    name: 'Link Information'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: true
      autoNoReferrer: true
      customTextMaxLength: 0
      customTextRequired: true
      defaultLinkName: asset
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: true
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: ''
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  074609d1-90b2-4a51-a98f-a64d2dc87363: # Link Style
    columnSuffix: krayzwno
    contentColumnType: string
    fieldGroup: null
    handle: linkStyle
    instructions: null
    name: 'Link Style'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Primary Button'
            -
              - value
              - primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Secondary Button'
            -
              - value
              - secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Link
            -
              - value
              - link
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: link
name: Link
sortOrder: 4
