field: 4fd5d92e-484c-47a3-b63b-5443cb2736db # Content
fieldLayouts:
  a26c7f91-ea25-47df-936e-218d2e3b574a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 683a4e58-0d04-4452-9b24-4f228753d538 # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1a4d7bb-9e26-4beb-8f12-f1cec91a5cca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bbc55cf3-b109-4433-a808-c8e0cece2e55
        userCondition: null
fields:
  683a4e58-0d04-4452-9b24-4f228753d538: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 2
