dateModified: 1725050338
email:
  fromEmail: samuelreichor@gmail.com
  fromName: Default
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    49638297-5169-4a05-8a97-3cbc65f4d29a: Default # Default
    f1b75f00-f4ed-4958-8a70-45714133b929: Default # Default
system:
  edition: solo
  live: true
  name: Default
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
