columnSuffix: null
contentColumnType: string
fieldGroup: be62c9df-631a-4395-99fc-94e2eda37b7b # ContentBuilder
handle: contentBuilder
instructions: null
name: Content
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentbuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
