columnSuffix: smzrngtc
contentColumnType: text
fieldGroup: 709d1f4c-cde7-4279-b196-7dbd0d3c1d4a # HeroSection
handle: heroHeadline
instructions: null
name: Headline
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
