columnSuffix: aepjnemi
contentColumnType: boolean
fieldGroup: 1e51ec97-9959-4860-8d78-a37833c6a526 # Common
handle: lightSwitch
instructions: null
name: 'Light Switch'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
