defaultPlacement: end
enableVersioning: true
entryTypes:
  - 0411514a-5a41-4ca8-8863-3d076e5aa670 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f1b75f00-f4ed-4958-8a70-45714133b929: # Default
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
