fieldLayouts:
  b6d794da-b613-4e05-8fae-6fb46137865a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d590edf5-61fc-4992-9094-1786f0e2d73a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 9c1606ff-3d28-445b-8694-af96007dd523
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1a6fb051-ad40-4976-811b-de8f4ae5d694 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9ba10cb-b299-4e6d-990c-a61055cf8be5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1bfe3fcd-e223-424b-b843-738840969c27
        userCondition: null
fs: graphics
handle: graphics
name: Graphics
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
